In [141]:
!pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.10/dist-packages (2.15.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.9.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: ml-dtypes~=0.2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.25.2)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow) (24.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.20.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow) (67.7.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.4.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (4.11.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.36.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.62.1)
Requirement already satisfied: tensorboard<2.16,>=2.15 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.15.2)
Requirement already satisfied: tensorflow-estimator<2.16,>=2.15.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.15.0)
Requirement already satisfied: keras<2.16,>=2.15.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.15.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow) (0.43.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (2.27.0)
Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (1.2.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (3.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (2.31.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (3.0.2)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (5.3.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (0.4.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow) (1.3.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (2024.2.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.16,>=2.15->tensorflow) (2.1.5)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (0.6.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow) (3.2.2)

***AIM OF THE PROJECT ***


The main aim of the project is to predict based on the bank details whether the customer has exited the bank or not.

In [142]:
import tensorflow as tf

print(tf.__version__)

2.15.0

In [143]:
# import all the necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [144]:
# reading the dataset
dataset = pd.read_csv('/content/Churn_Modelling.csv')

In [145]:
# display the first five rows of the dataset
print(dataset.head())

   RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42
1          2    15647311      Hill          608     Spain  Female   41
2          3    15619304      Onio          502    France  Female   42
3          4    15701354      Boni          699    France  Female   39
4          5    15737888  Mitchell          850     Spain  Female   43

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1
1       1   83807.86              1          0               1
2       8  159660.80              3          1               0
3       1       0.00              2          0               0
4       2  125510.82              1          1               1

   EstimatedSalary  Exited
0        101348.88       1
1        112542.58       0
2        113931.57       1
3         93826.63       0
4         79084.10       0

In [146]:
print(dataset.info)

<bound method DataFrame.info of       RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42
1             2    15647311       Hill          608     Spain  Female   41
2             3    15619304       Onio          502    France  Female   42
3             4    15701354       Boni          699    France  Female   39
4             5    15737888   Mitchell          850     Spain  Female   43
...         ...         ...        ...          ...       ...     ...  ...
9995       9996    15606229   Obijiaku          771    France    Male   39
9996       9997    15569892  Johnstone          516    France    Male   35
9997       9998    15584532        Liu          709    France  Female   36
9998       9999    15682355  Sabbatini          772   Germany    Male   42
9999      10000    15628319     Walker          792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1
1          1   83807.86              1          0               1
2          8  159660.80              3          1               0
3          1       0.00              2          0               0
4          2  125510.82              1          1               1
...      ...        ...            ...        ...             ...
9995       5       0.00              2          1               0
9996      10   57369.61              1          1               1
9997       7       0.00              1          0               1
9998       3   75075.31              2          1               0
9999       4  130142.79              1          1               0

      EstimatedSalary  Exited
0           101348.88       1
1           112542.58       0
2           113931.57       1
3            93826.63       0
4            79084.10       0
...               ...     ...
9995         96270.64       0
9996        101699.77       0
9997         42085.58       1
9998         92888.52       1
9999         38190.78       0

[10000 rows x 14 columns]>

In [147]:
print(dataset.describe())

         RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000
mean    76485.889288       1.530200      0.70550        0.515100
std     62397.405202       0.581654      0.45584        0.499797
min         0.000000       1.000000      0.00000        0.000000
25%         0.000000       1.000000      0.00000        0.000000
50%     97198.540000       1.000000      1.00000        1.000000
75%    127644.240000       2.000000      1.00000        1.000000
max    250898.090000       4.000000      1.00000        1.000000

       EstimatedSalary        Exited
count     10000.000000  10000.000000
mean     100090.239881      0.203700
std       57510.492818      0.402769
min          11.580000      0.000000
25%       51002.110000      0.000000
50%      100193.915000      0.000000
75%      149388.247500      0.000000
max      199992.480000      1.000000

In [148]:
# divide the dataset into independent and dependent features

dataset_x = dataset.iloc[:,3:13]

dataset_y = dataset.iloc[:,13]

In [149]:
print(dataset_x)

      CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1
1             608     Spain  Female   41       1   83807.86              1
2             502    France  Female   42       8  159660.80              3
3             699    France  Female   39       1       0.00              2
4             850     Spain  Female   43       2  125510.82              1
...           ...       ...     ...  ...     ...        ...            ...
9995          771    France    Male   39       5       0.00              2
9996          516    France    Male   35      10   57369.61              1
9997          709    France  Female   36       7       0.00              1
9998          772   Germany    Male   42       3   75075.31              2
9999          792    France  Female   28       4  130142.79              1

      HasCrCard  IsActiveMember  EstimatedSalary
0             1               1        101348.88
1             0               1        112542.58
2             1               0        113931.57
3             0               0         93826.63
4             1               1         79084.10
...         ...             ...              ...
9995          1               0         96270.64
9996          1               1        101699.77
9997          0               1         42085.58
9998          1               0         92888.52
9999          1               0         38190.78

[10000 rows x 10 columns]

In [150]:
print(dataset_y)

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

**FEATURE ENGINEERING**

In [151]:
geography = pd.get_dummies(dataset['Geography'], drop_first = True)


gender    = pd.get_dummies(dataset['Gender'], drop_first = True)

In [152]:
geography['Germany'] = geography['Germany'].astype('int')

geography['Spain'] = geography['Spain'].astype('int')

gender['Male'] = gender['Male'].astype('int')

In [153]:
# concatenate the varibales with the dataframe

# first drop the columns
dataset_x = dataset_x.drop(['Geography','Gender'], axis = 1)

In [154]:
dataset_x.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,42,2,0.00,1,1,1,101348.88
1,608,41,1,83807.86,1,0,1,112542.58
2,502,42,8,159660.80,3,1,0,113931.57
3,699,39,1,0.00,2,0,0,93826.63
4,850,43,2,125510.82,1,1,1,79084.10

In [155]:
dataset_x = pd.concat([dataset_x,geography, gender], axis = 1 )

In [156]:
print(dataset_x.head())

   CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1
1          608   41       1   83807.86              1          0
2          502   42       8  159660.80              3          1
3          699   39       1       0.00              2          0
4          850   43       2  125510.82              1          1

   IsActiveMember  EstimatedSalary  Germany  Spain  Male
0               1        101348.88        0      0     0
1               1        112542.58        0      1     0
2               0        113931.57        0      0     0
3               0         93826.63        0      0     0
4               1         79084.10        0      1     0

In [157]:
# spliiting the dataste into training and testing data
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(dataset_x, dataset_y, test_size = 0.2, random_state = 0)

In [158]:
X_train

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Germany,Spain,Male
7389,667,34,5,0.00,2,1,0,163830.64,0,1,0
9275,427,42,1,75681.52,1,1,1,57098.00,1,0,1
2995,535,29,2,112367.34,1,1,0,185630.76,0,0,0
5316,654,40,5,105683.63,1,1,0,173617.09,0,1,1
356,850,57,8,126776.30,2,1,1,132298.49,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
9225,594,32,4,120074.97,2,1,1,162961.79,1,0,0
4859,794,22,4,114440.24,1,1,1,107753.07,0,1,0
3264,738,35,5,161274.05,2,1,0,181429.87,0,0,1
9845,590,38,9,0.00,2,1,1,148750.16,0,1,0
2732,623,48,1,108076.33,1,1,0,118855.26,1,0,0

In [159]:
X_test

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Germany,Spain,Male
9394,597,35,8,131101.04,1,1,1,192852.67,1,0,0
898,523,40,2,102967.41,1,1,0,128702.10,0,0,0
2398,706,42,8,95386.82,1,1,1,75732.25,0,1,0
5906,788,32,4,112079.58,1,0,0,89368.59,0,0,1
2343,706,38,5,163034.82,2,1,1,135662.17,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...
1037,625,24,1,0.00,2,1,1,180969.55,0,0,0
2899,586,35,7,0.00,2,1,0,70760.69,0,0,0
9549,578,36,1,157267.95,2,1,0,141533.19,0,1,1
2740,650,34,4,142393.11,1,1,1,11276.48,1,0,1
6690,573,30,8,127406.50,1,1,0,192950.60,1,0,1

**FEATURE SCALING**

In [160]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()


# train the model
X_train = sc.fit_transform(X_train)

X_test  = sc.transform(X_test) # transform is only used in test data to avoid data leakage

In [161]:
X_train

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]])

In [162]:
X_test

array([[-0.55204276, -0.36890377,  1.04473698, ...,  1.75486502,
        -0.57369368, -1.09168714],
       [-1.31490297,  0.10961719, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       [ 0.57162971,  0.30102557,  1.04473698, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       ...,
       [-0.74791227, -0.27319958, -1.37744033, ..., -0.5698444 ,
         1.74309049,  0.91601335],
       [-0.00566991, -0.46460796, -0.33936434, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-0.79945688, -0.84742473,  1.04473698, ...,  1.75486502,
        -0.57369368,  0.91601335]])

In [163]:
X_train.shape

(8000, 11)

In [164]:
X_test.shape

(2000, 11)

**ARTIFICIAL NEURAL NETWORKS**

In [165]:
# import the libraries for Artificial Neural Networks

import keras
from   keras.models import Sequential
from   keras.layers import Dense

In [166]:
from   keras.layers import Dropout

In [167]:
# initialize the ann model
ann = Sequential()

# Adding the first input layer
ann.add(Dense(11,activation = 'relu'))


# Adding the first hidden layer
ann.add(Dense(7, activation = 'relu'))

# Adding the second hidden layer
ann.add(Dense(6, activation = 'relu'))

# Adding the output layer
ann.add(Dense(1, activation = 'sigmoid'))

In [168]:
# compile the ANN Model
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [169]:
import tensorflow as tf

early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    min_delta=0.0001,
    patience=20,
    verbose=1,
    mode="auto",
    baseline=None,
    restore_best_weights=False,
    start_from_epoch=0,
)

In [170]:
# Train the ANN Model
ann.fit(X_train, Y_train, validation_split = 0.33, batch_size = 10, epochs = 1000, callbacks = early_stopping)

Epoch 1/1000
536/536 [==============================] - 3s 4ms/step - loss: 0.5098 - accuracy: 0.7854 - val_loss: 0.4590 - val_accuracy: 0.7955
Epoch 2/1000
536/536 [==============================] - 2s 4ms/step - loss: 0.4375 - accuracy: 0.7962 - val_loss: 0.4429 - val_accuracy: 0.7955
Epoch 3/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.4253 - accuracy: 0.7962 - val_loss: 0.4338 - val_accuracy: 0.7955
Epoch 4/1000
536/536 [==============================] - 2s 3ms/step - loss: 0.4145 - accuracy: 0.8080 - val_loss: 0.4244 - val_accuracy: 0.8073
Epoch 5/1000
536/536 [==============================] - 2s 5ms/step - loss: 0.3993 - accuracy: 0.8274 - val_loss: 0.4113 - val_accuracy: 0.8156
Epoch 6/1000
536/536 [==============================] - 2s 4ms/step - loss: 0.3814 - accuracy: 0.8369 - val_loss: 0.3953 - val_accuracy: 0.8311
Epoch 7/1000
536/536 [==============================] - 3s 6ms/step - loss: 0.3639 - accuracy: 0.8489 - val_loss: 0.3852 - val_accuracy: 0.8357
Epoch 8/1000
536/536 [==============================] - 3s 6ms/step - loss: 0.3548 - accuracy: 0.8517 - val_loss: 0.3779 - val_accuracy: 0.8451
Epoch 9/1000
536/536 [==============================] - 3s 6ms/step - loss: 0.3484 - accuracy: 0.8569 - val_loss: 0.3733 - val_accuracy: 0.8482
Epoch 10/1000
536/536 [==============================] - 3s 5ms/step - loss: 0.3438 - accuracy: 0.8597 - val_loss: 0.3732 - val_accuracy: 0.8474
Epoch 11/1000
536/536 [==============================] - 2s 4ms/step - loss: 0.3419 - accuracy: 0.8572 - val_loss: 0.3711 - val_accuracy: 0.8466
Epoch 12/1000
536/536 [==============================] - 4s 8ms/step - loss: 0.3395 - accuracy: 0.8634 - val_loss: 0.3709 - val_accuracy: 0.8470
Epoch 13/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3396 - accuracy: 0.8608 - val_loss: 0.3703 - val_accuracy: 0.8459
Epoch 14/1000
536/536 [==============================] - 2s 3ms/step - loss: 0.3372 - accuracy: 0.8593 - val_loss: 0.3716 - val_accuracy: 0.8444
Epoch 15/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3367 - accuracy: 0.8595 - val_loss: 0.3713 - val_accuracy: 0.8463
Epoch 16/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3348 - accuracy: 0.8632 - val_loss: 0.3739 - val_accuracy: 0.8417
Epoch 17/1000
536/536 [==============================] - 2s 3ms/step - loss: 0.3339 - accuracy: 0.8628 - val_loss: 0.3712 - val_accuracy: 0.8451
Epoch 18/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3332 - accuracy: 0.8614 - val_loss: 0.3707 - val_accuracy: 0.8459
Epoch 19/1000
536/536 [==============================] - 2s 3ms/step - loss: 0.3331 - accuracy: 0.8643 - val_loss: 0.3721 - val_accuracy: 0.8444
Epoch 20/1000
536/536 [==============================] - 2s 4ms/step - loss: 0.3312 - accuracy: 0.8612 - val_loss: 0.3716 - val_accuracy: 0.8451
Epoch 21/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3312 - accuracy: 0.8632 - val_loss: 0.3709 - val_accuracy: 0.8463
Epoch 22/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3309 - accuracy: 0.8636 - val_loss: 0.3706 - val_accuracy: 0.8440
Epoch 23/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3299 - accuracy: 0.8656 - val_loss: 0.3702 - val_accuracy: 0.8451
Epoch 24/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3294 - accuracy: 0.8625 - val_loss: 0.3728 - val_accuracy: 0.8444
Epoch 25/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3294 - accuracy: 0.8614 - val_loss: 0.3733 - val_accuracy: 0.8482
Epoch 26/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3286 - accuracy: 0.8653 - val_loss: 0.3717 - val_accuracy: 0.8444
Epoch 27/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3284 - accuracy: 0.8642 - val_loss: 0.3714 - val_accuracy: 0.8482
Epoch 28/1000
536/536 [==============================] - 2s 3ms/step - loss: 0.3278 - accuracy: 0.8668 - val_loss: 0.3721 - val_accuracy: 0.8466
Epoch 29/1000
536/536 [==============================] - 2s 4ms/step - loss: 0.3277 - accuracy: 0.8638 - val_loss: 0.3723 - val_accuracy: 0.8448
Epoch 30/1000
536/536 [==============================] - 2s 3ms/step - loss: 0.3274 - accuracy: 0.8640 - val_loss: 0.3725 - val_accuracy: 0.8459
Epoch 31/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3264 - accuracy: 0.8638 - val_loss: 0.3710 - val_accuracy: 0.8482
Epoch 32/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3262 - accuracy: 0.8647 - val_loss: 0.3714 - val_accuracy: 0.8474
Epoch 33/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3259 - accuracy: 0.8675 - val_loss: 0.3760 - val_accuracy: 0.8429
Epoch 34/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3257 - accuracy: 0.8655 - val_loss: 0.3781 - val_accuracy: 0.8432
Epoch 35/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3252 - accuracy: 0.8638 - val_loss: 0.3742 - val_accuracy: 0.8466
Epoch 36/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3245 - accuracy: 0.8711 - val_loss: 0.3713 - val_accuracy: 0.8448
Epoch 37/1000
536/536 [==============================] - 1s 3ms/step - loss: 0.3247 - accuracy: 0.8671 - val_loss: 0.3797 - val_accuracy: 0.8432
Epoch 38/1000
536/536 [==============================] - 2s 4ms/step - loss: 0.3242 - accuracy: 0.8662 - val_loss: 0.3713 - val_accuracy: 0.8489
Epoch 39/1000
536/536 [==============================] - 2s 3ms/step - loss: 0.3235 - accuracy: 0.8660 - val_loss: 0.3732 - val_accuracy: 0.8459
Epoch 40/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3224 - accuracy: 0.8679 - val_loss: 0.3740 - val_accuracy: 0.8482
Epoch 41/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3230 - accuracy: 0.8640 - val_loss: 0.3752 - val_accuracy: 0.8455
Epoch 42/1000
536/536 [==============================] - 2s 3ms/step - loss: 0.3224 - accuracy: 0.8662 - val_loss: 0.3749 - val_accuracy: 0.8459
Epoch 43/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3209 - accuracy: 0.8688 - val_loss: 0.3850 - val_accuracy: 0.8353
Epoch 43: early stopping

In [171]:
# prediction for the test data
pred_y = ann.predict(X_test)

63/63 [==============================] - 0s 2ms/step

In [172]:
print(pred_y)

[[0.4670763 ]
 [0.48130584]
 [0.14682448]
 ...
 [0.51261014]
 [0.24751645]
 [0.13967258]]

In [173]:
pred_y = (pred_y >= 0.5)

In [174]:
print(pred_y)

[[False]
 [False]
 [False]
 ...
 [ True]
 [False]
 [False]]

In [175]:
# make the confusion matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test, pred_y)

In [176]:
print(cm)

[[1437  158]
 [ 164  241]]

In [177]:
# Accuracy of the model
from sklearn.metrics import accuracy_score

ac = accuracy_score(pred_y, Y_test)

print(ac)

0.839

In [178]:
# get the weights of the neural networks
ann.get_weights()

[array([[-7.49249682e-02,  1.67201325e-01, -1.37043968e-01,
         -2.96109527e-01, -3.29186097e-02,  2.20906399e-02,
         -7.29324698e-01, -7.38192871e-02,  2.68231452e-01,
          5.21562509e-02, -2.98683643e-01],
        [ 9.98439044e-02, -3.37926626e-01,  6.56586409e-01,
          2.17062518e-01, -5.76038938e-03,  2.12414384e-01,
         -4.73531187e-02,  6.28899395e-01, -5.99944234e-01,
         -5.54798067e-01,  2.90887058e-01],
        [-2.16993801e-02,  8.77576247e-02, -9.47002992e-02,
          1.90549567e-01, -4.49960902e-02, -6.89441040e-02,
          5.40643632e-01,  2.48278961e-01,  2.95898557e-01,
         -2.14509174e-01, -4.88201492e-02],
        [-3.77670109e-01,  3.58221412e-01,  1.80439875e-01,
          4.06060636e-01,  2.38600045e-01,  4.08696443e-01,
         -3.24487448e-01, -8.22516024e-01, -3.12552094e-01,
         -1.45527393e-01,  3.83080155e-01],
        [-1.30298102e+00, -2.58604318e-01,  9.37365592e-01,
         -4.11113918e-01, -8.60325173e-02,  7.76079655e-01,
          7.73309886e-01, -5.70916049e-02,  3.64178985e-01,
          8.53736699e-02,  2.33809531e-01],
        [ 1.26666605e-01, -5.05643725e-01,  1.77409038e-01,
          5.20172715e-01,  6.82538986e-01,  7.45385746e-03,
          2.79352311e-02,  6.31549433e-02, -1.07144497e-01,
          2.31933575e-02,  1.81783348e-01],
        [-4.17843133e-01,  9.20531377e-02, -4.46797498e-02,
          1.52146250e-01,  2.91270524e-01, -4.90851998e-01,
         -5.63088395e-02,  5.35544991e-01, -3.17611694e-01,
         -3.81007224e-01,  1.39977172e-01],
        [ 1.14227116e-01, -3.94872613e-02,  5.02671778e-01,
          3.01169932e-01,  3.52795362e-01, -1.05532013e-01,
         -4.42282200e-01, -2.01503292e-01,  1.45836934e-01,
          2.00269074e-04,  5.76578856e-01],
        [ 3.11630160e-01, -5.56707680e-01, -3.44737649e-01,
          4.70633898e-03, -3.40203941e-01,  5.42003512e-02,
         -1.70564801e-01,  1.68975487e-01, -1.13265134e-01,
          4.52889502e-02, -3.51977617e-01],
        [-6.92306459e-02,  3.09754521e-01, -2.28987724e-01,
         -1.88462846e-02,  4.37386930e-01,  8.04895833e-02,
         -1.03953525e-01,  2.10160241e-01,  2.88731344e-02,
         -2.80410796e-01, -7.01773316e-02],
        [-8.42492580e-02,  3.49587679e-01,  2.33205482e-01,
         -6.32965386e-01,  5.61042786e-01, -1.27696618e-01,
         -4.71214414e-01,  3.57746959e-01,  8.77864957e-01,
          3.67171764e-02, -2.20646426e-01]], dtype=float32),
 array([ 0.36093414,  0.42748037, -0.24729276,  0.15166156,  0.34125888,
         0.02313416,  0.2804245 , -0.0244264 ,  0.40043753,  0.66443866,
        -0.31546286], dtype=float32),
 array([[-0.43238524,  0.48559296,  0.77927357,  0.66756773, -0.3993571 ,
         -0.4262034 , -0.32044357],
        [ 0.5418238 , -0.590473  ,  0.22932228,  0.23486207, -0.07308967,
         -0.45630115, -0.4845587 ],
        [-0.56704676,  0.12397187,  0.28143153, -0.10230733,  0.24896663,
          0.2565437 ,  0.3961489 ],
        [ 0.06596199,  0.03588554, -0.4690581 , -0.94779456,  0.12345936,
         -0.22152384, -1.0791657 ],
        [ 0.01169861,  0.36203364,  0.06290296,  0.04375116,  0.393253  ,
         -0.2388103 ,  0.05196726],
        [ 0.18370277,  0.36836147,  0.27936807,  0.59504384, -0.70393175,
         -0.1823464 ,  0.36380684],
        [ 0.59859896,  0.69885856,  0.57894933, -0.22730213,  0.38735482,
         -0.29732195,  0.25517055],
        [-0.44826797,  0.3841524 , -0.07098607,  0.4589837 ,  0.6729062 ,
          0.426578  , -0.15993078],
        [-0.03924625, -0.26630226,  0.48098177, -0.02213207,  0.51716465,
          0.02420933,  0.22425535],
        [ 0.2224428 , -0.38352323, -0.58212256, -0.0958734 ,  0.7691676 ,
          0.21969931,  0.19455306],
        [-0.38776144, -0.07579525,  0.5858195 ,  0.2410888 , -0.35807493,
          0.69967455, -0.18877836]], dtype=float32),
 array([ 0.45385787, -0.2982834 , -0.12995984, -0.26257458,  0.4199492 ,
         0.33713865, -0.4989954 ], dtype=float32),
 array([[-0.5127178 ,  0.11638922, -0.51212525,  0.0474714 ,  0.28539765,
          0.6959859 ],
        [ 0.4772277 , -1.2579688 , -0.85108435, -0.26400867, -0.02589897,
         -0.22604562],
        [ 1.098515  , -0.541735  ,  0.23924285,  0.47744516, -1.379318  ,
         -0.1611523 ],
        [ 0.24064377, -0.3850085 , -0.43409926,  0.14085412,  0.00780486,
         -0.35114768],
        [-0.67480946, -0.8069461 ,  0.6187365 , -0.66017324,  0.3627218 ,
          0.6087476 ],
        [ 0.1306422 ,  0.22921604,  0.88276327, -0.41738963,  0.11326755,
          0.9090838 ],
        [ 1.1666054 , -0.34888852, -0.4918756 , -0.24105883,  0.03502086,
         -0.83993787]], dtype=float32),
 array([ 0.00803211,  0.18805993, -0.03499592, -0.01457718, -0.3606293 ,
         0.4685077 ], dtype=float32),
 array([[ 0.9065884 ],
        [ 1.1853002 ],
        [-0.5959411 ],
        [ 0.46893576],
        [ 0.7899043 ],
        [-1.1420345 ]], dtype=float32),
 array([0.01334463], dtype=float32)]